// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        agp_version = '9.2.1'
        kotlin_version = '2.0.21'
    }
    repositories {
        mavenCentral()
        google()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$agp_version"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

// common in all sub-projects
subprojects {
}

ext {
    // Android config.
    coreMinSdkVersion = 21
    coreCompileSdkVersion = 37
    coreTargetSdkVersion = 37
    coreVersionName = '5.8.0'
    defaultVersionCode = 1
    webbridgeMinSdkVersion = 21
    samsungReferrerMinSdkVersion = 21
    vivoReferrerMinSdkVersion = 23
    samsungCloudDevMinSdkVersion = 23

    // POM.
    adjustGroupId = 'com.adjust.sdk'
}

allprojects {
    repositories {
        mavenCentral()
        google()
    }
    gradle.projectsEvaluated {
        tasks.withType(JavaCompile) {
            options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
        }
    }
}
